[build]
  # El comando para construir tu aplicaci칩n
  command = "npm run build"
  # El directorio donde se encuentran tus archivos est치ticos
  publish = "public"
  # El directorio donde se encuentran tus funciones de Netlify
  functions = "."

[functions]
  # Los m칩dulos externos que usas en tus funciones
  external_node_modules = ["express", "sequelize", "cookie-session", "method-override", "ejs"]
  # El paquete que usas para empaquetar tus funciones
  node_bundler = "esbuild"

[[redirects]]
  # Una regla de redirecci칩n para que Express pueda manejar las rutas que empiezan con /api
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/index/:splat"

